### ISSUE TITLE
Please show translation statistics

### ISSUE THREAD

**Issue by Gryllida** [splitbrain/dokuwiki-plugin-translation#100]
For each language, translation statistics:

- Which pages are translated up to how much percent (if you track paragraph by paragraph translation)
- Which translated pages are outdated, and by how much
- Which pages have missing translations

Another software example screenshots

Pootle
----
![Screenshot](https://wiki.deimos.fr/images/5/55/Pootle_screenshot.png)

TranslateWiki
----
![Screenshot](http://4.bp.blogspot.com/_s7edsEQHKvk/TSWSnFyMKmI/AAAAAAAACcw/7PhAKyl4ghc/s1600/Screenshot-8.png)

**Comment by splitbrain** [comment]
there's some of what you want in the admin interface. I won't implement the rest. PRs welcome though.

**Comment by Gryllida** [comment]
Hi splitbrain, thank you.

1) May the thing show in non-admin interface too to engage more translators, so they know which parts need more work?

2) I do not think you want to close it,

if someone is looking for good issues to fix, they do not browse closed issues. 

On this bug tracker, how do you open the issue and set a low priority?
