### ISSUE TITLE
[Feature Request] - Unique title (URL) per language

### ISSUE THREAD

**Issue by sennewood** [splitbrain/dokuwiki-plugin-translation#109]
Hello, I'm woking on a wiki with german as the primary language. The plugin works very well, but one thing bothers me: If I want to translate **de:festung**, the english page is called **en:festung**. Since the plugin has to pick a (default) name that's fine, but I found no way to tell the plugin that I want **en:fortress** as the real name (URL) of that page.

**Comment by splitbrain** [comment]
That's how the plugin works. Using local language page names would require some kind of lookup table. That would be a different plugin.
