### ISSUE TITLE
Update to Release 2017-02-19a "Frusterick Manners"  translation links not show

### ISSUE THREAD

**Issue by MetaAbstract** [splitbrain/dokuwiki-plugin-translation#115]
After update to this release translation links not show. I reinstall plugin - but result same.

**Comment by splitbrain** [comment]
works for me. how did you integrate the plugin? maybe the update overwrote some manual changes you did to the template?

**Comment by MetaAbstract** [comment]
I am very sorry, but i forget about translation link code insert in main.php. You can close the issue.
