### ISSUE TITLE
No language switch depending on NS

### ISSUE THREAD

**Issue by jlAlice** [splitbrain/dokuwiki-plugin-translation#116]
The plugin does not switch to another language depending on NS. If to add "`global $lang;`" in lines about number 214 of action.php it starts to  switch properly. Please see, maybe, there's another problem, I'm not a programer, I found it by comparing with old version of the plugin.

**Comment by splitbrain** [comment]
fixed in 93a7d7ac08368e24df0d1f5d00a27d27081a0976
