### ISSUE TITLE
Header text is not translated

### ISSUE THREAD

**Issue by vladipus** [splitbrain/dokuwiki-plugin-translation#119]
Was kind of surprised to see that the header text is not translated at all. "Recent Changes", "Sitemap" and others are always in their default language.
Am I the only one getting this?
![2017-03-23 18_40_51-ru_start turbopedia](https://cloud.githubusercontent.com/assets/468323/24256216/9af5e444-0ff8-11e7-98b2-4ca7ee9a5ec0.png)

**Comment by splitbrain** [comment]
fixed in 93a7d7ac08368e24df0d1f5d00a27d27081a0976

**Comment by vladipus** [comment]
This fixed the issue for me. Thank you for your work here, guys. Great software!
