### ISSUE TITLE
[feature] Config options to translate wiki's title and tagline

### ISSUE THREAD

**Issue by vladipus** [splitbrain/dokuwiki-plugin-translation#120]
Would like to have an option to translate the wiki's title and the optional tagline. Something like:
```php
$conf['title.ru'] = 'Турбопедия';
$conf['tagline.ru'] = 'Знания начинаются здесь!';
```

**Comment by gianfrus** [comment]
It would be very useful, I think it's a lack feature in the translation plugin.
I tried some "quick 'n dirty" workaround but yet no luck!

**Comment by kondurake** [comment]
I ran into the same problem, and as a _workaround_ I developed the [plugin:localization](https://www.dokuwiki.org/plugin:localization).

@splitbrain What do you think? Can we merge the same functional into [plugin:translation](https://www.dokuwiki.org/plugin:translation)?

**Comment by splitbrain** [comment]
I don't see it in the scope of this plugin.
