### ISSUE TITLE
"conf/lang/<ISO>/lang.php" isn't  reflected when the "translateui" is "1" 

### ISSUE THREAD

**Issue by jyagasaki** [splitbrain/dokuwiki-plugin-translation#125]
Hi,

When the "translateui" is "1", "conf/lang/\<ISO\>/lang.php" isn't  reflected on my dokuwiki except root  name space with default language. 

Is this right behavior ?

Regards,
J.Yagasaki

**Comment by splitbrain** [comment]
should be fixed with c7d31b725a5072414f6aaf923928a2d4e6752acb
