### ISSUE TITLE
PHP Warning since upgrade to Greebo

### ISSUE THREAD

**Issue by Natenom** [splitbrain/dokuwiki-plugin-translation#134]
`PHP Warning: Declaration of syntax_plugin_translation::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /.../lib/plugins/translation/syntax.php on line 0`

**Comment by splitbrain** [comment]
This file doesn't even exist anymore. Update your plugins.
