### ISSUE TITLE
Double slash in URL

### ISSUE THREAD

**Issue by zuglufttier** [splitbrain/dokuwiki-plugin-translation#137]
I use the translation plugin with two namespaces for two languages (de and en) and it's working just fine.

But there is one problem: On the start page, and only there, is a double slash in the URL like this: https://www.example.com//de/start

All other links are just fine, I have `useslash` enabled in the config.

**Comment by nesetril** [comment]
The same for me: https://dataearth.cz/doku.php//cs/start. However this shows up only when clicking on the logo in the right top corner.

**Comment by zuglufttier** [comment]
Excellent, the commit https://github.com/dsb-ccb-solutions/dokuwiki-plugin-translation/commit/ce72e85e9bb16fcd2bd8350d54095ab83554d69b seems to do the trick.

**Comment by nesetril** [comment]
Me too – now it works. Thanks.
