### ISSUE TITLE
Titles of toolbar buttons not translated

### ISSUE THREAD

**Issue by selfthinker** [splitbrain/dokuwiki-plugin-translation#18]
The titles of the toolbar buttons (e.g. "Bold Text [B]") is not translated when you are in a different language (and the rest of the interface is translated). The `/lib/exe/js.php` gets only created for the main language...

This is related to #7, as both things (JS and CSS creation) happen before the language change.

**Comment by splitbrain** [comment]
this was fixed a while ago, but also got revamped with c7d31b725a5072414f6aaf923928a2d4e6752acb
