### ISSUE TITLE
False flag

### ISSUE THREAD

**Issue by nesetril** [splitbrain/dokuwiki-plugin-translation#237]
After the latest update a false flag appeared linking erroneously the root namespace.
https://dataearth.cz/doku.php/en/start
![obrazek](https://user-images.githubusercontent.com/21980999/44024427-8c23fac0-9eed-11e8-9585-39a07d75b352.png)
![obrazek](https://user-images.githubusercontent.com/21980999/44024483-b00090c0-9eed-11e8-9c84-1b71481079fb.png)

**Comment by nesetril** [comment]
I have manually changed the `helper.php` file and the problem was solved.

**Comment by SergeySCHU** [comment]
Tell me, what need to do to fix?
