### ISSUE TITLE
Automatic link to translated pages

### ISSUE THREAD

**Issue by innodan** [splitbrain/dokuwiki-plugin-translation#247]
I use a Dokuwiki with main language Englisch and translations in German.

Some pages are only available in German. If I navigate to the Englisch page, I get the message that the page does not exist.

Is it possible to show the German translation instead of the message?

**Comment by nesetril** [comment]
Past ~~NOTRANS~~ to the German page, then the language switcher will hide and the users will not be confused.

**Comment by innodan** [comment]
Thanks for the request.

`~~NOTRANS~~` is a possibility to prohibit user´s confusion but i have to use the german links. 

I would like the following solution: Link to the English page. If wiki recognizes that there is only the german translation open the german page. If there is created an English translation later on open the English translation.

**Comment by nesetril** [comment]
OK, I got it. There are options I know about:
https://www.dokuwiki.org/faq:redirect
https://www.dokuwiki.org/plugin:pageredirect
https://www.dokuwiki.org/plugin:include
