### ISSUE TITLE
sidebar translation

### ISSUE THREAD

**Issue by willbelr** [splitbrain/dokuwiki-plugin-translation#25]
The primary language of my wiki is french. I use the arctic template which include a sidebar, acting like an index of the whole wiki.

I would like that if someone switches to english version, on any page, the sidebar automatically switches to en:sidebar.

exemple of the issue:
http://odeur.comuv.com/doku.php?id=en:wiki:syntax

Thank you.

**Comment by splitbrain** [comment]
sidebars are now a core feature and different namespaces can have their own sidebar
