### ISSUE TITLE
Interlingual _template support

### ISSUE THREAD

**Issue by Rainbow-Spike** [splitbrain/dokuwiki-plugin-translation#255]
I use `ru/sci-fi/freefall/_template.txt` for starting new comic issue translation in Russian folder. But sometimes French editor starts his translation earlier than me. And `fr/sci-fi/freefall/_template.txt` may be obsolete because of a link to comic stripe have a "centurificated" path `{{http://freefall.purrsia.com/ff3300/fc0@PAGE@.png}}`. The `ru/sci-fi/freefall/_template.txt` has a newer "ff3400" path.

I need that `fr/<path>` folder would directly detect `_template.txt` in `other_language/<path>` folders. Maybe through an empty file `_ru.txt` into `ru/<path>/_template.txt`. Can you help me?

**Comment by Dr-Yukon** [comment]
This system can be generally useful for prioritizing languages in a plugin
