### ISSUE TITLE
notification links cant be clicked

### ISSUE THREAD

**Issue by icf20** [splitbrain/dokuwiki-plugin-translation#259]
![image](https://user-images.githubusercontent.com/17784575/69886644-4dc73b00-12e3-11ea-8ca4-240d4357a16f.png)

`<div class="notify">This translation is older than the <a href="/wiki/doku.php?id=snip" class="wikilink1">original page</a> and might be outdated. See what has <a href="/wiki/doku.php?id=snip&amp;do=diff&amp;rev=1575053066" class="wikilink1">changed</a>.</div>`

i am testing this on top of yunohost so i dont know if there is any issue with ynh overlay

**Comment by splitbrain** [comment]
can't reproduce this
