### ISSUE TITLE
Improve accessiblity

### ISSUE THREAD

**Issue by Zatalyz** [splitbrain/dokuwiki-plugin-translation#261]
Hello,
A friend found an accessibility problem on the plugin display. "It is necessary to put the text which precedes the list in label". After exploring, I think I corrected this, in the helper.php file.

ligne 233, base :
```
$out .= '<span>' . $this->getLang('translations');
if($this->getConf('about')) $out .= $this->showAbout();
$out .= ':</span> ';
```
			
Change to :
```
$out .= '<label for="translate">' . $this->getLang('translations');
if($this->getConf('about')) $out .= $this->showAbout();
$out .= ':</label> ';
```

ligne 261, base :
`$out .= '<select name="id" class="' . $class . '">';`

change to :
`$out .= '<select name="id" id="translate" class="' . $class . '">';`

I submit pull request when I found how make it :)

**Comment by splitbrain** [comment]
form elements have been removed with 6605eed0b71c3a4cad3020b84ec65e9c5f03578a
