### ISSUE TITLE
No Language Selection With "Hogfather"

### ISSUE THREAD

**Issue by 7Saturn** [splitbrain/dokuwiki-plugin-translation#267]
I finally managed to update to "Hogfather" but all of a sudden the language selection box on article pages is missing. I still can access articles with their full name, switching the language manually. I can also still see the list of untranslated articles ("outdated and missing translations") just fine, so the extension is active in part. The problem appears for both modes, the drop down field as well as the variation without drop down menu. In both cases no selection appears any more.
![11-06-_2020_17-21-05](https://user-images.githubusercontent.com/11319934/84405080-f6961180-ac07-11ea-8934-e26085d7c388.png)

**Comment by 7Saturn** [comment]
Anybody having this problem? I even tried to disable all other plugins, that could be deactivated, but still, no luck.

**Comment by fkrauthan** [comment]
How did you get the plugin to load in first place @7Saturn ? I had to disable this plugin as it was not conforming with the extension interface after updating to Hogfather.

**Comment by 7Saturn** [comment]
Well, I did have quite a fight with some of my plugins for »Hogfather«. I deactivated some of them and did the upgrades (during that time, several updates came within a few days). But eventually I am working now on »Release rc-2020-06-09 "Hogfather" RC3« and at least my installations works mostly fine. But the plugin apparently does not have its desired effect any more. It is still active and visible in the configuration, but the language selection does not show any more.

**Comment by splitbrain** [comment]
The plugin is just working fine for me on Hogfather. How exactly do you have it integrated?

**Comment by 7Saturn** [comment]
Simply installed it at some point, I believe via the internal search & install function, and then upgraded to Hogfather. I am hesitant to reinstall it, as I am not sure whether I will loose my settings this way. If this is not the case, I might simply try and reinstall it.

**Comment by splitbrain** [comment]
The translation plugin does not just simply work. It needs to be either embedded in your template or your sidebar. See the docs.

**Comment by 7Saturn** [comment]
Damn, you are right. I remember now. And in my backups this is still present. It probably vanished when I was updating Hogfather manually...
