### ISSUE TITLE
fix suggestion 2 documentation

### ISSUE THREAD

**Issue by icf20** [splitbrain/dokuwiki-plugin-translation#271]
`Suggestion 2: For the “dokuwiki”-template you can create sidebarheader.html within lib/tpl/dokuwiki with the code above. Then it looks like the “DokuWiki.org” Homepage and you need not redo this after a dokuwiki update. `

what is that even suppose to mean? put the file and ask santa to make things happen?

a better version is

Suggestion 2: For the “dokuwiki”-template you can create sidebarheader.html within lib/tpl/dokuwiki with the code above. _After that create a wiki page with the name **sidebar** and save it_.Then it looks like the “DokuWiki.org” Homepage and you need not redo this after a dokuwiki update.

**Comment by splitbrain** [comment]
it's a wiki. go ahead and improve the text.
