### ISSUE TITLE
Add `lang` and `dir` to main content if `translateui` is off

### ISSUE THREAD

**Issue by selfthinker** [splitbrain/dokuwiki-plugin-translation#273]
When the `translateui` setting is not used, the page's language is still set to the wiki's main language and there is no indication in the code that the language of the main content has changed.
That will be bad for translation services (like Google Translate) and screenreader users.

The main content should have a `lang` and `dir` around it to make the language (and script direction) be programmatically determinable. The `dir` will then also help to show text in the correct direction.
See also splitbrain/dokuwiki#3413.

Adding `lang` and `dir` to the main content is not necessary when `translateui` is set, as the `html` element will have the correct attributes for the whole page.

**Comment by splitbrain** [comment]
Makes sense. Should be possible with the TPL_CONTENT_DISPLAY event
