### ISSUE TITLE
Improve poor contrast for accessibility

### ISSUE THREAD

**Issue by Badatos** [splitbrain/dokuwiki-plugin-translation#277]
Hello,
First, thank you for this usefull plugin :)
There is a poor contrast color in your style.  To improve accessibility, can you make a small change in the file "style.css" (line 72) :
```
.dokuwiki div.plugin_translation option.wikilink2 {
    color: #808080;
```

this color could me more contrasted with background if you darken it, for example :
```
.dokuwiki div.plugin_translation option.wikilink2 {
    color: #575757;
```

**Comment by splitbrain** [comment]
styles have been adjusted in 6605eed0b71c3a4cad3020b84ec65e9c5f03578a
