### ISSUE TITLE
langnames.txt is missing by default

### ISSUE THREAD

**Issue by psschn** [splitbrain/dokuwiki-plugin-translation#284]
Hello I have installed the plug-in, but unfortunately the file `langnames.txt` (actually found under `lib/plugins/translation/lang/langnames.txt` was not installed or is missing in the current version. 
That's why I had to create it myself. Please adapt in the next version or at least describe somewhere how to create this file.

**Like this :**
In the file level of Dokuwiki "`lib/plugins/translation/lang/`" create the file "langnames.txt". Now per line:
`<language-code><space><name to be displayed>.
`
Example for English:
`en English`

Thanks

**Comment by splitbrain** [comment]
Hmm? The file hasn't been touched in 12 years and is still at the same location: https://github.com/splitbrain/dokuwiki-plugin-translation/blob/master/lang/langnames.txt 

Just to be sure I downloaded the plugin, and sure enough, it's there.

**Comment by psschn** [comment]
Yes, thank you, I could have thought of that. I know now why the file is missing with me. I downloaded the plugin from the Downalds.DokuWiki page https://download.dokuwiki.org/ and not from GitHub, in the version some files are missing. That's the reason, no wonder it doesn't work. But that's not your fault.

One more question:
The current version of your plugin does not work with the Bootstrap3 theme. Did you rename a function somewhere, because only the language switcher crashes, before everything works fine. I will have to work with an old version of the plugin now, because the new one doesn't work with the template. But I dare to doubt that someone else has the template fixed. Therefore I ask if you had an idea for a quick fix?

Log:
```
2023-03-16 20:54:00
Error: Call to undefined method helper_plugin_translation::getTransItem()
<ROOT>/lib/tpl/bootstrap3/tpl/translation.php(31)
#0 <ROOT>/lib/tpl/bootstrap3/tpl/navbar.php(89): include_once()
#1 <ROOT>/lib/tpl/bootstrap3/main.php(51): require_once('<ROOT>')
#2 <ROOT>/inc/actions.php(27): include('<ROOT>')
#3 <ROOT>/doku.php(126): act_dispatch()
#4 {main}
```

If not, it is not bad, it still works with the older version, but that is not the best solution for the problem.

Greetings

> Übrigens falls das leichter ist können wir auch auf Deutsch wechseln 😊

**Comment by splitbrain** [comment]
issue reported at https://github.com/dokuwiki/download.dokuwiki.org/issues/10
