### ISSUE TITLE
"Deutsch" missing in the langnames.txt file for informal

### ISSUE THREAD

**Issue by ikabod** [splitbrain/dokuwiki-plugin-translation#286]
The following line is missing after "de Deutsch":
de-informal Deutsch

**Comment by splitbrain** [comment]
PR please

**Comment by ikabod** [comment]
Not sure if I did it correct:

https://github.com/splitbrain/dokuwiki-plugin-translation/commit/add1ebd635884eec4e5c416ee9909c8e819fab30
