### ISSUE TITLE
Suggestion : seach limit

### ISSUE THREAD

**Issue by ics01** [splitbrain/dokuwiki-plugin-translation#292]
Dear Sir,

When, in a multilingual wiki, you make a search, the search function retrieve all the concernet pages in all languages. 

May I suggest the ability for the search fonction to retrieve only the page in the language you are ((for example, in the Google search screen, there is a combo that allows you to choose between a search in all pages, and a search limited to pages in the language of the browser country) ?

Anyway, thank you for the great job of Dokuwiki. We love it ! 💘 

Etienne

**Comment by splitbrain** [comment]
use https://www.dokuwiki.org/config:search_nslimit for that

**Comment by ics01** [comment]
Vielen Dank, lieber Herr Gohr!
Ich hätte es selbst sehen sollen, entschuldigen Sie, dass ich Ihre Zeit verschwendet habe.
Vielen Dank für Ihre Wiki-Engine, die wir hier in Paris ohne Moderation nutzen. 🥇 
Etienne
