### ISSUE TITLE
Suggestion: hide non-existent translations in the list 

### ISSUE THREAD

**Issue by SergeySCHU** [splitbrain/dokuwiki-plugin-translation#320]
Do not display languages ​​in the list for which there is no translation.
Currently they are displayed in gray.
The thing is that some pages have fewer translations than others and I would not like to display non-existent translations for the current page.

**Comment by splitbrain** [comment]
Showing missing translations is intentional as it allows user to navigate there and create the translations. If you don't want that, you can always use a user style to not display them.
