### ISSUE TITLE
trouble with redirectstart and a default language

### ISSUE THREAD

**Issue by Eldertoon** [splitbrain/dokuwiki-plugin-translation#51]
Hi,

Following the wiki, I have two options :
    a default language in the root namespace and translations in sub namespaces
    no pages in the top namespace and all languages in sub namespaces

Since my wiki was already in french and I just wanted to translate it in english, I choosed option 1. The only issue I have is that all my french page links are like help:mypage and in the traductions I need to put en:help:mypage.

Seeing the redirectstart, I give it a try and there seem to be a bug. My original config is :
$conf['plugin']['translation']['translations'] = 'en';
$conf['plugin']['translation']['translateui'] = 1;
$conf['plugin']['translation']['checkage'] = 1;

So I added the line : 
$conf['plugin']['translation']['redirectstart'] = 1;

The result is that all my french wiki is in english. If I connect with a fr or en browser, I am redirected to en:help:mypage even if I force the page http://mywiki/help:mypage.

So I changed the line : 
$conf['plugin']['translation']['translations'] = 'en,fr';

The result is pretty much the same since everything is now translated. If I connect with a fr browser I'm redirected to the (non existing) fr:help:mypage. With an en browser I go to en:help:mypage.

My question is : is redirectstart option available only if having a wiki with no top namespace ? Did I miss a default language / skip translate option ?

Regards,

**Comment by splitbrain** [comment]
closing this as probably too old to be of any consequence
