### ISSUE TITLE
No selector by default on the wiki or with code in sidebar doesn't work

### ISSUE THREAD

**Issue by melodie11** [splitbrain/dokuwiki-plugin-translation#52]
Hello,

First, thank you for all your great work.

I just installed DokuWiki here http://wiki.linuxvillage.org along with Monobook, English and French, and the plugins : Translation, Open Office Export2, Wrap, Gallery, Fckg and Captcha. 

So far I can't find any button anywhere to select French or English. I have configured it the best possible, read the docs. I tried to switch to the themes Vector, and a little later to the default DokuWiki theme : there is still no translation button.

I have asked help on the IRC channel, where someone has done tests on his test Dokuwiki, and it seems there are issues in the code. Hopefully if there is something needing an update in the code you will find the fix.

Regards,
Mélodie

**Comment by splitbrain** [comment]
closing this, assuming it has been fixed with recent changes
