### ISSUE TITLE
RTL UI languages don't load RTL styles

### ISSUE THREAD

**Issue by selfthinker** [splitbrain/dokuwiki-plugin-translation#7]
When switching to an RTL language (he, ar, etc) with "translateui" on, the UI switches to the language accordingly, but the rtl styles don't load.

**Comment by daffneele** [comment]
This is old but I just had the same issue for Bootstrap theme. 
So just in case any one else is looking for this- 
For Bootstrap3: http://dokuwiki.org/template:bootstrap3
In your main.php
above line 34 (before the foreach)
add
    <?php if($lang['direction'] == 'rtl'){ 
       array_push( $bootstrapStyles , DOKU_TPL.'assets/bootstrap/css/bootstrap-rtl.min.css'); 
      } 
     ?>

**Comment by splitbrain** [comment]
should be fixed with c7d31b725a5072414f6aaf923928a2d4e6752acb
