### ISSUE TITLE
Call to undefined method cache::__construct()

### ISSUE THREAD

**Issue by ricrogz** [splitbrain/dokuwiki-plugin-translation#74]
Hi, I'm getting this message all over my apache error_log.

I guess it is related with the last change in source (https://github.com/splitbrain/dokuwiki-plugin-translation/commit/00e502327399e80a4feaa459af3d9be5c66ab378), since it consisted basically in enabling this call instead of the previous cache::cache.

Reverting back to the previous code seems to fix the error (at least, no more error messages on each page hit).

I'm quite new to dokuwiki, so I don't know which relevant information to include here, besides using Apache2.4 mpm-event, php-fpm and latest stable version of Dokuwiki (2014-09-29d "Hrun") and translation plugin (up to last change in code at 22-05-2015, which seems to produce the issue), but I (think) I can provide any needed information, just ask for it.

**Comment by konilabs** [comment]
Hi there,
I have exactly the same issue as ricrogz since translation plugin update.
Reverting the change fix the issue.

I found this because indexmenu was not displayed correctly.

Regards,

**Comment by dturkalj** [comment]
Hi, same problem here. It looks that this change block java script code on pages in non default language namespace (indexmenu plugin on sidebar doesn't show javascript menu on non-default languages). I also revert code and it fix the problem.
Have two wiki instances: one on Win2003 / IIS6 / PHP 5.4.41; other on Win2008 R2 / IIS7 / PHP 5.5.9.
both use latest Dokuwiki (2014-09-29d "Hrun").
