### ISSUE TITLE
Call to undefined function getRevisions()

### ISSUE THREAD

**Issue by LMS235** [splitbrain/dokuwiki-plugin-translation#98]
After upgrade to the newest version we got this error:

[Tue Jul 12 16:34:50.311855 2016] [:error] [pid 10748134:tid 4884] [client xxxxx] PHP Fatal error:  Call to undefined function getRevisions() in /path/wiki/lib/plugins/translation/helper.ph
p on line 396, referer: https://server/doku.php?id=xxx:xxx:xxx

**Comment by splitbrain** [comment]
should be fixed since cde890455b9b1b5336c41f840c0c44a84e6231f6

**Comment by LMS235** [comment]
i think this is not the same error

your fix is for line 369 the error is in 396

as workaround i add the <code>public function getRevisions</code> as normal <code>function getRevisionsBUGFIX</code> and changed the the faulty line.

The first time the error occour was after running the cleanup plugin. Perhaps it there a connection with the old versions?
